version: '5'

services:
  spring-boot-app:
    image: springdockercompose
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cloud_vendor
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: cloud_vendor



version: "5"
services:
  enggadda:
    image: mongo:latest
    container_name: "enggadda"
    ports:
      - 27017:27017
  springdockercompose:
    image: springdockercompose:latest
    container_name: "springdockercompose"
    ports:
      - 9090:8080
    links:
      - enggadda

